### ISSUE TITLE
The messages sic-sp-name and sic-sp-title appear to be unused

### ISSUE THREAD

**Issue by amire80** [ArchiXL/SmartComments#1]
The messages sic-sp-name and sic-sp-title appear only in the messages json files, and not anywhere else in the code. Their content is just the extension name. If they are not actually used anywhere, they should be deleted from the extension code.

If I'm missing something, and the messages are actually used, there should be a comment in the code that helps to find them, according to the convention described in https://www.mediawiki.org/wiki/Help:System_message#Using_messages . It should probably be explained in the qqq documentation, too.

**Comment by YOUR1** [comment]
Merged, thanks.
