### ISSUE TITLE
Error "Jfcherng\Diff\DiffHelper" not found

### ISSUE THREAD

**Issue by mtettke123** [ArchiXL/SmartComments#12]
## Setup

- MW version: 1.39
- PHP version: 8.1.20
- DB system (MySQL, Blazegraph, etc.) and version: MySQL

## Issue

when opening a page after a mediawiki restart, sometimes the error message
`[3ba4c1886a165aa23530032f] /index.php/TESTSEITE Error: Class "Jfcherng\Diff\DiffHelper" not found`
appears. Reloading seems to help.

## Steps to reproduce:

?

**Comment by YOUR1** [comment]
I've updated the installation steps. In detail, you can fix the problem through composer.


To enable Composer to discover and process the composer.json file that's included in the extensions, add this to $IP/composer.local.json
```json
"extra": {
      "merge-plugin": {
          "include": [
              "extensions/SmartComments/composer.json"
          ]
      }
  }
```

**Comment by mtettke123** [comment]
mediawiki 1.39 docker does not include composer. Any other way to install the dependency?

**Comment by mtettke123** [comment]
as php-diff seems to have own dependencies, I tried to install composer within the docker. This works, although the container is altered afterwards, so one should maybe build an own container. But works in general.
