### ISSUE TITLE
Add message documentation (qqq)

### ISSUE THREAD

**Issue by amire80** [ArchiXL/SmartComments#3]
There is no qqq documentation for this extension at all.

It must be added to all the messages according to the conventions described at https://www.mediawiki.org/wiki/Help:System_message#Message_documentation .

Without message documentation, it's very hard to translate the extensions correctly. Just as a small sample, the messages "Manual" (`sic-manual`), "Comment" (`sic-input-newcomment`), and "Reply" (`sic-input-commenttext`) are impossible to translate correctly into languages in which these words have different translations for when they verbs, nouns, or adjectives.

**Comment by YOUR1** [comment]
We've decided to manually do translations, thus closing this issue.
