### ISSUE TITLE
sic-rn-backto is a lego message

### ISSUE THREAD

**Issue by amire80** [ArchiXL/SmartComments#4]
The message `sic-rn-backto` is what's called a "lego message" in MediaWiki developers jargon. It is concatenated in run time with another string at `src/SpecialPage/Special.php` line 58.

Instead of concatenating, `[[Special:SmartComments]]` must be passed as a parameter (`$1`).

See https://www.mediawiki.org/wiki/Help:System_message#Avoid_fragmented_or_%22patchwork%22_messages for helpful documentation about it.

**Comment by YOUR1** [comment]
We've decided to manually do translations, thus closing this issue.
