### ISSUE TITLE
What is the BeforeDataUpdateComplete hook?

### ISSUE THREAD

**Issue by pppery** [ArchiXL/SmartComments#5]
This extension defines a hook registration named "BeforeDataUpdateComplete". I can't find any other references to this hook across the entire MediaWiki ecosystem. Did you mean to use `SMW::Store::BeforeDataUpdateComplete` instead?

**Comment by YOUR1** [comment]
Good catch. This should be the hook you mentioned indeed. We'll take care of this issue in the next release.

**Comment by robinwiel** [comment]
Thanks for the question! It seems that we started replacing the deprecated hook "SMWStore::updateDataBefore" with "SMW::SQLStore::BeforeDataUpdateComplete" but didn't finish it yet. This will be fixed in the next tagged release version 1.5.1, which we will release after merging #8.
